# Generated by Django 3.0.3 on 2020-03-05 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('matches', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportingRequest',
            fields=[
                ('location', models.CharField(max_length=128)),
                ('sessionID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=128)),
                ('duration', models.DurationField(blank=True, default=1)),
                ('status', models.BooleanField(default=True)),
                ('involved_users', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='involved_users', to='main.UserProfile')),
                ('start_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start_user', to='main.UserProfile')),
            ],
        ),
    ]
