# Generated by Django 3.0.3 on 2020-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('sessionID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('pageURL', models.CharField(max_length=128, unique=True)),
                ('sport', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('socialMedia', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
