# Generated by Django 3.0.3 on 2020-03-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=128)),
                ('sessionID', models.CharField(max_length=16)),
                ('sport', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='connectercise', max_length=128)),
                ('password', models.CharField(default='password', max_length=128)),
                ('pageURL', models.URLField(blank=True)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('sport', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('socialMedia', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
