# Generated by Django 3.0.3 on 2020-03-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportingrequest',
            name='sport',
            field=models.CharField(default='swimming', max_length=128),
        ),
        migrations.AlterField(
            model_name='sportingrequest',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sportingrequest',
            name='sessionID',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pageURL',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='socialMedia',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sport',
            field=models.CharField(max_length=128),
        ),
    ]
