# Generated by Django 3.0.3 on 2020-03-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200302_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportingrequest',
            name='sessionID',
            field=models.IntegerField(max_length=64, unique=True),
        ),
    ]
