# Generated by Django 3.0.3 on 2020-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200302_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportingrequest',
            name='location',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sportingrequest',
            name='sessionID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportingrequest',
            name='sport',
            field=models.CharField(max_length=128),
        ),
    ]
