# Generated by Django 3.0.3 on 2020-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200302_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportingrequest',
            name='location',
            field=models.CharField(default='glasgow', max_length=128, unique=True),
        ),
    ]
