# Generated by Django 3.0.3 on 2020-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200302_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportingrequest',
            name='sessionID',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
