# Generated by Django 3.0.3 on 2020-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200302_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportingrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='sportingrequest',
            name='sessionID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='socialMedia',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
