# Generated by Django 3.0.3 on 2020-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
