# Generated by Django 3.0.3 on 2020-03-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectercise', '0002_auto_20200307_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
