# Generated by Django 3.0.3 on 2020-03-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectercise', '0003_sport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
